#
# Makefile for the video capture/playback device drivers.
#

obj-$(CONFIG_PXA_CAMERA)  += camera.o cam_host.o

obj-$(CONFIG_CI_CAMERA_GPIO_I2C)	+= i2c-gpio.o

obj-$(CONFIG_CI_TOSHIBA_VGA)	+= toshiba_vga.o
obj-$(CONFIG_CI_SAMSUNG_S5K4B)	+= samsung_s5k4b.o
obj-$(CONFIG_CI_SHARP_RJ63SC)	+= sharp_rj63sc_5m.o
obj-$(CONFIG_CI_SHARP_RJ6AB)	+= sharp_rj6ab.o
obj-$(CONFIG_CI_OV_2650)	+= ov2650.o
obj-$(CONFIG_CI_MT9D113)	+= mt9d113.o
obj-$(CONFIG_CI_MT9T111)	+= mt9t111.o
obj-$(CONFIG_CI_MCNEX_5M)	+= mcnex_5m.o
obj-$(CONFIG_CI_ALTEK_5M)	+= altek_5m.o
