#
#  linux/arch/arm/mach-pxa/imm/imm.h
#
#  Intel Memory Management
#
#  Makefile for the Intel Memory Management.
#
#  Todd Brandt
#  Copyright (c) 2004, Intel Corporation (todd.e.brandt@intel.com)
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#

# policy.c is the heart of the IMM code
obj-$(CONFIG_IMM) += policy.o
obj-$(CONFIG_IMM_API_SRAM) += sram.o ioremap.o

